# Generated by Django 5.0.2 on 2024-02-22 13:08

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان رویداد')),
                ('description', models.TextField(null=True, verbose_name='توضیحات وبینار')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع')),
                ('teacher', models.CharField(max_length=250, null=True, verbose_name='نام مدرس')),
                ('price', models.IntegerField(max_length=250, null=True, verbose_name='هزینه رویداد')),
                ('image', models.ImageField(upload_to='media/events', verbose_name='تصویر')),
                ('slug', models.CharField(max_length=255, null=True, verbose_name='لینک')),
                ('status', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_module.event', verbose_name='سمینار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شرکت کننده')),
            ],
        ),
    ]
