# Generated by Django 5.0.2 on 2024-02-22 13:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0002_alter_event_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع'),
        ),
    ]
