# Generated by Django 5.0.2 on 2024-02-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0005_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True, verbose_name='هزینه رویداد'),
        ),
    ]
