# Generated by Django 5.0.2 on 2024-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0006_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
