# Generated by Django 5.0.2 on 2024-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0007_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(max_length=255, verbose_name='تاریخ شروع'),
        ),
    ]
