# Generated by Django 5.0.2 on 2024-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0009_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total',
            field=models.IntegerField(default=0, verbose_name='هزینه کل'),
        ),
    ]
