# Generated by Django 5.0.2 on 2024-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0011_userdescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdescount',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
