# Generated by Django 5.0.2 on 2024-02-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0012_userdescount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='status',
        ),
    ]
