# Generated by Django 5.0.2 on 2024-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0014_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
