# Generated by Django 5.0.2 on 2024-02-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0018_event_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdescount',
            options={'verbose_name': 'کد استفاده شده', 'verbose_name_plural': 'کدهای استفاده شده'},
        ),
    ]
