# Generated by Django 5.0.2 on 2024-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0019_alter_userdescount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events', verbose_name='تصویر'),
        ),
    ]
