# Generated by Django 5.0.2 on 2024-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_module', '0020_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days_of_week',
            field=models.TextField(blank=True, null=True, verbose_name='روزهای برگزاری'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات رویداد'),
        ),
    ]
