"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q=@)995ed@bm2434s9mi943xzbsf*ubf#^z4di1vy43a19qips'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts_module.apps.AccountsModuleConfig',
    'events_module.apps.EventsModuleConfig',
    'manage_module.apps.ManageModuleConfig',
    'payment_module.apps.PaymentModuleConfig',

    'django_jalali',
    'sorl.thumbnail'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "accounts_module.User"

MERCHANT = "41af5198-62bc-4c31-af3a-424f4e73ec70" #empty

SANDBOX = False


'''
add axes and ...
  باید ب اپ ها اضاف بشه و همچنینaxes همچنین
  این میدل ویر ها 
'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    
    INSTALLED_APPS = [
    	'axes',
            ]

ی سری تنظیمات امنیتی اضاف کردم ک بعدا یادمون نره ولی ب نظرم تو زمان توسعه غیرفعال بمونن بهتره
'''
'''
##########################################3
#تنظیمات django-axes (برای جلوگیری از حملات Brute Force)
AXES_FAILURE_LIMIT = 5  # تعداد تلاش‌های ناموفق قبل از مسدودسازی
AXES_COOLOFF_TIME = 5*(1/60) # زمان به ساعت (مثلاً ۱ ساعت)
AXES_LOCKOUT_PARAMETERS = [[ "ip_address"]]
AXES_LOCKOUT_TEMPLATE = 'login_app/blocked.html'
AXES_RESET_ON_SUCCESS = True  # ریست تلاش‌های ناموفق پس از ورود موفق

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # اضافه کردن AxesBackend
    'django.contrib.auth.backends.ModelBackend',  # backend پیش‌فرض جنگو
]

#####################################33
#تنظیمات امنیتی SSL و HSTS
SECURE_SSL_REDIRECT = True  # کاربران را به HTTPS هدایت کن
SECURE_HSTS_SECONDS = 31536000  # فعال‌سازی HSTS برای یک سال
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  
SECURE_HSTS_PRELOAD = True  
#####################################
#تنظیمات Referrer Policy و XSS
SECURE_REFERRER_POLICY = "same-origin"
SECURE_BROWSER_XSS_FILTER = True  # جلوگیری از XSS در مرورگر
SECURE_CONTENT_TYPE_NOSNIFF = True  # جلوگیری از MIME Sniffing
######################################
#تنظیمات CSRF و Clickjacking
CSRF_COOKIE_SECURE = True  
CSRF_COOKIE_HTTPONLY = True  
X_FRAME_OPTIONS = "DENY"  # جلوگیری از Clickjacking
##################################################
#تنظیمات Session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60*30  # 30 دقیقه به ثانیه
SESSION_COOKIE_PATH = '/'  # کوکی برای کل سایت اعمال می‌شود
SESSION_COOKIE_SECURE = True  # اگر از HTTPS استفاده می‌کنید، این را True کنید
SESSION_COOKIE_HTTPONLY = True  # جلوگیری از دسترسی JavaSFript به کوکی
SESSION_COOKIE_SAMESITE = 'Lax'  # برای جلوگیری از حملات CSRF
SESSION_SAVE_EVERY_REQUEST = True
####################################
'''

