# Generated by Django 5.0.2 on 2024-02-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0002_alter_user_field_of_study'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'رشته', 'verbose_name_plural': 'رشته ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
