# Generated by Django 5.0.2 on 2024-02-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0003_alter_field_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
